### ISSUE TITLE
Add "onConnectionError" notification events

### ISSUE THREAD

**Issue by itvby** [cloudflare/speedtest#22]
Hi! Thanks for your work.

It would be a good idea to add "onConnectionError" to events.

Sometimes the application crashes due to an error calling the this.#loadEngine.stop() method because this.#loadEngine is not initialized. There is no way to catch this error.

![photo_2023-07-20_16-07-06](https://github.com/cloudflare/speedtest/assets/39412164/138da35d-c144-4f46-811e-b5bdf2bd6f24)

Thanks!

**Comment by bekmuradov** [comment]
I had the same issue, and I managed to solve it by making changes to the `BandwidthMeasurementEngine` class.
If you're interested in the fix and want to see the specific changes, you can find them in this pull request: https://github.com/cloudflare/speedtest/pull/24/files

**Comment by vasturiano** [comment]
@itvby thanks for reaching out. 

This bug has been fixed, and a new `onError` method has also been added to the module schema. Please upgrade to `v1.3.0` to get the fix.

More details on the PR: https://github.com/cloudflare/speedtest/pull/27
