### ISSUE TITLE
Infinite empty requests 

### ISSUE THREAD

**Issue by didoshotev** [cloudflare/speedtest#37]
When conducting a 15-second speed test, the API continues to make empty requests even after the test is completed. These requests persist until the browser tab is closed, resulting in thousands of unnecessary requests. This issue is intermittent but can be reproduced by opening multiple tabs in parallel.

![image](https://github.com/cloudflare/speedtest/assets/62618421/b676cead-9937-4aac-9c73-b3c19a022066)

**Comment by sj-andavisolutions** [comment]
This happens with default download/upload URLs. I deployed worker and added custom endpoints for download and upload and its not happening anymore.

**Comment by eugeniumegherea** [comment]
I've got the same problem, did you figure it out?
