### ISSUE TITLE
CORS problem

### ISSUE THREAD

**Issue by MockingMagician** [cloudflare/speedtest#38]
Hello :-)

Since today, we have been having CORS issues. The responses are being sent with 'speed.cloudflare.com' for the 'Access-Control-Allow-Origin' header.

```txt
Access to fetch at 'https://speed.cloudflare.com/__down?bytes=1048576' from origin 'http://localhost:8080' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header contains the invalid value 'speed.cloudflare.com'
```

This wasn't the case before.

Any idea why ?

**Comment by sj-andavisolutions** [comment]
Facing same issue since an hour or two.

**Comment by ishabodiwala** [comment]
Hello @MockingMagician, are you able to solve the issue?

**Comment by MockingMagician** [comment]
> Hello @MockingMagician, are you able to solve the issue?

Hello @ishabodiwala nope ! It still unresolved...

**Comment by jason5ng32** [comment]
Same here.

**Comment by didoshotev** [comment]
Hey, same here please resolve it we have thousands of users blocked right now.

**Comment by MockingMagician** [comment]
Hello @S2023P

I think you don't understand the problem, here speed-test is used in a web context. 

This comes directly from the speed-test API endpoints responding with `Access-Control-Allow-Origin: speed.cloudflare.com`.
 Previously, they responded with `Access-Control-Allow-Origin: *`.

That's why it fail

**Comment by jason5ng32** [comment]
We will not be able to solve, it must be solved by Cloudflare in the backend.
@dotjs @trickstival @vasturiano

**Comment by yigithanyucedag** [comment]
Any update on this?

**Comment by matthieugouel** [comment]
The issue has been fixed on Cloudflare's side, could you retry?
Sorry for the inconvenience.

**Comment by MockingMagician** [comment]
Thanks for the fixed @matthieugouel 

![Screenshot from 2024-07-18 09-50-34](https://github.com/user-attachments/assets/3cd26eaf-7477-4f0c-a93a-31098db7b569)

**Comment by MockingMagician** [comment]
Thanks for the fixed @matthieugouel 

![Screenshot from 2024-07-18 09-50-34](https://github.com/user-attachments/assets/3cd26eaf-7477-4f0c-a93a-31098db7b569)

**Comment by animencoding** [comment]
the issue is back see issue #39
