### ISSUE TITLE
`packetLoss` endpoint has CORS set to `speed.cloudflare.com`

### ISSUE THREAD

**Issue by 96imranahmed** [cloudflare/speedtest#39]
Hi there, the default config is failing because the `packetLoss` test queries `https://speed.cloudflare.com/turn-creds`

However, the CORS policy for this page is set to only accept cloudflare domains (e.g., `access-control-allow-origin: speed.cloudflare.com`)

A workaround is to remove packetLoss calculations from the test, but I'd love to be able to also use packetLoss stats in the reporting on my app!

**Comment by PrasanthGondi** [comment]
+1

**Comment by animencoding** [comment]
+1 having issues with the turn-creds CORS

**Comment by dragonslair1027** [comment]
@96imranahmed how did you do the workaround for packetLoss??

**Comment by 96imranahmed** [comment]
Sorry I wasn't clear - I don't have a solution for getting a packetLoss metric. I just ignore the test entirely by removing it from the list of default measurements that are run when you make a test. 

```
    { type: 'latency', numPackets: 1 }, // initial ttfb estimation
    { type: 'download', bytes: 1e5, count: 1, bypassMinDuration: true }, // initial download estimation
    { type: 'latency', numPackets: 20 },
    { type: 'download', bytes: 1e5, count: 9 },
    { type: 'download', bytes: 1e6, count: 8 },
    { type: 'upload', bytes: 1e5, count: 8 },
    { // Remove this line
      type: 'packetLoss',
      numPackets: 1e3,
      batchSize: 10,
      batchWaitTime: 10, // ms (in between batches)
      responsesWaitTime: 3000 // ms (silent time after last sent msg)
    },
    { type: 'upload', bytes: 1e6, count: 6 },
    { type: 'download', bytes: 1e7, count: 6 },
    { type: 'upload', bytes: 1e7, count: 4 },
    { type: 'download', bytes: 2.5e7, count: 4 },
    { type: 'upload', bytes: 2.5e7, count: 4 },
    { type: 'download', bytes: 1e8, count: 3 },
    { type: 'upload', bytes: 5e7, count: 3 },
    { type: 'download', bytes: 2.5e8, count: 2 }
 ```

**Comment by joao-reis** [comment]
We will apply a fix in the next days.

**Comment by dragonslair1027** [comment]
@joao-reis Please let me know when fix is released  :D

**Comment by joao-reis** [comment]
Fixed 👍

**Comment by 96imranahmed** [comment]
Works perfectly! Let me close this!
