### ISSUE TITLE
Packet loss test: TypeError: Cannot read properties of undefined (reading 'turnServerUser')

### ISSUE THREAD

**Issue by brcsw** [cloudflare/speedtest#42]
Steps:

1. Visit https://speed.cloudflare.com/
2. Wait a few seconds.

Expected: packet loss test runs.

Observed: packet loss test fails with this error:

> Unable to perform measurement: TypeError: Cannot read properties of undefined (reading 'turnServerUser')

<img width="606" alt="image" src="https://github.com/user-attachments/assets/a4d7e5fb-2bbb-47b6-872d-7d296c7b6e4b">

Configuration:

macOS Version 14.5 (Build 23F79)

Tried in two browsers:
- Chrome 128.0.6613.138 (Official Build) (arm64)
- Safari Version 17.5 (19618.2.12.11.6)

I'm not sure if this is a bug in the client, a problem with Cloudflare's servers, or a problem with my machine or network.

**Comment by mvhdfaiz** [comment]
I'm having the same error. Started around one or two days ago.

**Comment by animencoding** [comment]
it's an issue with CORS headers on cloudflare end, see issue #39
